add_definitions(-DBOOST_ERROR_CODE_HEADER_ONLY)

if (CARLA_BUILD_TYPE STREQUAL "Server")
  add_definitions(-DASIO_NO_EXCEPTIONS)
  add_definitions(-DBOOST_NO_EXCEPTIONS)
  add_definitions(-DLIBCARLA_NO_EXCEPTIONS)
  add_definitions(-DPUGIXML_NO_EXCEPTIONS)
endif ()

execute_process(COMMAND git describe --tags --dirty --always
    OUTPUT_VARIABLE CARLA_VERSION
    OUTPUT_STRIP_TRAILING_WHITESPACE
)

# Uncomment to force support for an specific image format (require their
# respective libraries installed).
# add_definitions(-DLIBCARLA_IMAGE_WITH_PNG_SUPPORT)
# add_definitions(-DLIBCARLA_IMAGE_WITH_JPEG_SUPPORT)
# add_definitions(-DLIBCARLA_IMAGE_WITH_TIFF_SUPPORT)

add_definitions(-DLIBCARLA_TEST_CONTENT_FOLDER="${LIBCARLA_TEST_CONTENT_FOLDER}")

set(BOOST_INCLUDE_PATH ${BOOST_INSTALL_DIR}/include)
set(BOOST_LIB_PATH ${BOOST_INSTALL_DIR}/lib)

if (CARLA_BUILD_TYPE STREQUAL "Server")
  # Here libraries linking libc++.
  set(RPCLIB_INCLUDE_PATH ${RPCLIB_SERVER_INSTALL_DIR}/include)
  set(RPCLIB_LIB_PATH ${RPCLIB_SERVER_INSTALL_DIR}/lib)
  set(GTEST_INCLUDE_PATH ${GTEST_SERVER_INSTALL_DIR}/include)
  set(GTEST_LIB_PATH ${GTEST_SERVER_INSTALL_DIR}/lib)
elseif (CARLA_BUILD_TYPE STREQUAL "Client")
  # Here libraries linking libstdc++.
  set(RPCLIB_INCLUDE_PATH ${RPCLIB_CLIENT_INSTALL_DIR}/include)
  set(RPCLIB_LIB_PATH ${RPCLIB_CLIENT_INSTALL_DIR}/lib)
  set(GTEST_INCLUDE_PATH ${GTEST_CLIENT_INSTALL_DIR}/include)
  set(GTEST_LIB_PATH ${GTEST_CLIENT_INSTALL_DIR}/lib)
  set(RECAST_INCLUDE_PATH ${RECAST_CLIENT_INSTALL_DIR}/include)
  set(RECAST_LIB_PATH ${RECAST_CLIENT_INSTALL_DIR}/lib)
  set(LIBPNG_INCLUDE_PATH ${LIBPNG_CLIENT_INSTALL_DIR}/include)
  set(LIBPNG_LIB_PATH ${LIBPNG_CLIENT_INSTALL_DIR}/lib)
elseif (CARLA_BUILD_TYPE STREQUAL "ros2")
  set(FASTDDS_INCLUDE_PATH ${FASTDDS_INSTALL_DIR}/include)
  set(FASTDDS_LIB_PATH ${FASTDDS_INSTALL_DIR}/lib)
  list(APPEND CMAKE_PREFIX_PATH ${FASTDDS_INSTALL_DIR})
elseif (CARLA_BUILD_TYPE STREQUAL "Pytorch")
  list(APPEND CMAKE_PREFIX_PATH ${LIBTORCH_PATH})
  list(APPEND CMAKE_PREFIX_PATH ${LIBTORCHSCATTER_INSTALL_DIR})
  list(APPEND CMAKE_PREFIX_PATH ${LIBTORCHCLUSTER_INSTALL_DIR})
  list(APPEND CMAKE_PREFIX_PATH ${LIBTORCHSPARSE_INSTALL_DIR})
endif ()

if(TRAVIS)
  add_definitions(-DLIBCARLA_IMAGE_WITH_PNG_SUPPORT=false)
else()
  add_definitions(-DLIBCARLA_IMAGE_WITH_PNG_SUPPORT=true)
endif(TRAVIS)
